logger:
  enabled: true
notifier:
  mail:
    enabled: true
    address: postfix
    port: 25
    user_name: anonymizer@example.com
    password: password
    enable_starttls_auto: false
    to: somebody@example.com
    from: anonymizer@example.com
dump_server:
  host: example.com
  user: anonymizer
  port: 22
  passphrase:
  path: /path/to/dumps/directory
database:
  user: root
  host: 127.0.0.1
  pass: 
web_data_path: ./web/data
tmp_path: /tmp
cap:
  ssh_options:
    keys: 
      - /path/to/private/ssh/key/for/deployment